# Generated by Django 5.2.8 on 2025-12-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rachels', '0003_vendor_remove_record_details_record_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200, verbose_name='Name')),
                ('paid_on', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
    ]
