# Generated by Django 5.2.8 on 2025-12-10 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rachels', '0004_advancesalary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('Dulari', 'Dulari'), ('Pours and Plates', 'Pours and Plates'), ('Rachels', 'Rachels'), ('Rachels1', 'Rachels1'), ('Rachels2', 'Rachels2')], max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
