# Generated by Django 5.2.8 on 2026-01-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rachels', '0005_managerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoritem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('ml', 'Millilitre'), ('pcs', 'Pieces'), ('carton', 'Carton'), ('packet', 'Packet')], default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='vendoritem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
